namespace GenericTestingFramework.Core.Models;

/// <summary>
/// Defines the type of test to be executed
/// </summary>
public enum TestType
{
    /// <summary>
    /// User Interface testing (web, mobile, desktop)
    /// </summary>
    UI,
    
    /// <summary>
    /// Application Programming Interface testing
    /// </summary>
    API,
    
    /// <summary>
    /// Combined UI and API testing in the same scenario
    /// </summary>
    Mixed,
    
    /// <summary>
    /// Database testing
    /// </summary>
    Database,
    
    /// <summary>
    /// Performance and load testing
    /// </summary>
    Performance
}

/// <summary>
/// Represents the current status of a test scenario
/// </summary>
public enum TestStatus
{
    /// <summary>
    /// Test scenario has been created but not yet finalized
    /// </summary>
    Draft,
    
    /// <summary>
    /// Test scenario has been generated by AI/LLM
    /// </summary>
    Generated,
    
    /// <summary>
    /// Test scenario is ready for execution
    /// </summary>
    Ready,
    
    /// <summary>
    /// Test scenario is currently being executed
    /// </summary>
    Running,
    
    /// <summary>
    /// Test scenario execution completed successfully
    /// </summary>
    Completed,
    
    /// <summary>
    /// Test scenario execution failed
    /// </summary>
    Failed,
    
    /// <summary>
    /// Test scenario has been cancelled
    /// </summary>
    Cancelled,
    
    /// <summary>
    /// Test scenario is temporarily disabled
    /// </summary>
    Disabled
}

/// <summary>
/// Priority levels for test execution
/// </summary>
public enum TestPriority
{
    /// <summary>
    /// Low priority test
    /// </summary>
    Low = 1,
    
    /// <summary>
    /// Medium priority test
    /// </summary>
    Medium = 2,
    
    /// <summary>
    /// High priority test
    /// </summary>
    High = 3,
    
    /// <summary>
    /// Critical priority test that must be executed first
    /// </summary>
    Critical = 4
}

/// <summary>
/// Execution environments for tests
/// </summary>
public enum TestEnvironment
{
    /// <summary>
    /// Development environment
    /// </summary>
    Development,
    
    /// <summary>
    /// Testing/QA environment
    /// </summary>
    Testing,
    
    /// <summary>
    /// Staging environment
    /// </summary>
    Staging,
    
    /// <summary>
    /// Production environment
    /// </summary>
    Production,
    
    /// <summary>
    /// User Acceptance Testing environment
    /// </summary>
    UAT
}